In [337]:
import os

In [341]:
mydir = '/opt/pytorch/demo/checkpoints/20220523/bci_comp4a/'

for file in os.listdir(mydir):
    splitted_name = file.split('_')
    if splitted_name[-1] == 'agents':
        print(file)
        os.remove(os.path.join(mydir, file))

In [223]:
from collections import namedtuple, deque

Experience = namedtuple("Experience",
                        ("states", "actions", "next_states"))
deq = deque([], maxlen=100)

In [224]:
deq.append(Experience(2, 3, 1))
deq.append(Experience(4, 5, None))
deq.append(Experience(2, 3, 3))
deq.append(Experience(4, 5, None))

len(deq)

4

In [225]:
rand = random.sample(deq, 2)
rand


[Experience(states=2, actions=3, next_states=1),
 Experience(states=4, actions=5, next_states=None)]

In [226]:
batch = Experience(*zip(*rand))
batch

Experience(states=(2, 4), actions=(3, 5), next_states=(1, None))

In [227]:
l = batch.next_states
tuple(map(lambda s: s is not None, l))

(True, False)

In [302]:
import torch

states = torch.tensor([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
action = torch.tensor([2, 1, 0])

In [303]:
states

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [304]:
torch.tensor([states[i].max(dim=-1)[1] for i in range(3)])

tensor([2, 2, 2])

In [320]:
from itertools import count

done = False
for t in count():
    print(t)
    if t == 10:
        break
        if t == 5:
            break

0
1
2
3
4
5
6
7
8
9
10


In [327]:
a = torch.tensor([1.])
b = torch.tile(a, (16, 1))
torch.mean(b)

tensor(1.)

In [324]:
torch.tile(a, (1, 13)).shape

torch.Size([1, 13])

In [343]:
import torch 
t = torch.tensor([0.0003, 0.0003])
t.max(dim=-1)[-1]

tensor(0)

In [359]:
s = range(32)
import random
ind = random.sample(s, 2)
t = torch.tensor([[0.0003], [0.0003], [0], [1], [2]])
t

tensor([[3.0000e-04],
        [3.0000e-04],
        [0.0000e+00],
        [1.0000e+00],
        [2.0000e+00]])

In [362]:
torch.mean(t, axis=-1)

tensor([3.0000e-04, 3.0000e-04, 0.0000e+00, 1.0000e+00, 2.0000e+00])

In [361]:
t.shape

torch.Size([5, 1])

In [358]:
import os
os.getcwd()

'/opt/pytorch/demo/logs'